const CONST_VAR = {
	SORT_DESC: 'desc',
	SORT_ASC: 'asc',
	PAGINATION_SIZE: 5,
	NEXT_PAGE_TITLE: 'NEXT',
	PRE_PAGE_TITLE: 'PREV',
	FIRST_PAGE_TITLE: 'FIRST',
	LAST_PAGE_TITLE: 'LAST',
	PAGE_START_INDEX: 1,
	PAGE_SIZE_LIST: [ 10, 25, 50, 100 ]
}

export default CONST_VAR
